# Generated by Django 4.2.17 on 2025-01-06 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField()),
                ('surface_ut', models.FloatField()),
                ('production', models.FloatField()),
                ('insee', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('prod', models.IntegerField()),
                ('prod_class', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
